export const userData: any[] = [
    {
        ID:1,                    
        UserTypeID:1,      
        FirstName: "John",      
        LastName : "Smith",       
        Phone    : "9879879871",      
        Email    : "john@gmail.com",      
        PasswordHash: "$2a$12$6fq.WvngzI19a8S9HCi14e.FlQz9sWnfdM4dbP7hIVYCzmv4XYUdO",   
        PasswordSalt:"$gjhghj$" ,     
        IsActive     : true,  
        AuthenticationTypeID:1,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:2,                    
        UserTypeID:2,      
        FirstName: "Joe",      
        LastName : "Smith",       
        Phone    : "9879999871",      
        Email    : "joe@gmail.com",      
        PasswordHash: "#gghuydfsgiuhu$fgddf",   
        PasswordSalt:"$gjhgbvchj$" ,  
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:3,                    
        UserTypeID:1,      
        FirstName: "Aleena",      
        LastName : "Smith",       
        Phone    : "98799871",      
        Email    : "aleena@gmail.com",      
        PasswordHash: "#gghuygiuhu$fgddf",   
        PasswordSalt:"$gjhedagfghj$" , 
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:4,                    
        UserTypeID:3,      
        FirstName: "tina",      
        LastName : "Smith",       
        Phone    : "987900879871",      
        Email    : "tina@gmail.com",      
        PasswordHash: "#gghuyghu$fgddf",   
        PasswordSalt:"$gjhghj$" , 
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:5,                    
        UserTypeID:3,      
        FirstName: "Sam",      
        LastName : "Smith",       
        Phone    : "984479879871",      
        Email    : "sam@gmail.com",      
        PasswordHash: "#gghbuygiuhu$fgddf",   
        PasswordSalt:"$gjhvbghj$" ,  
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:6,                    
        UserTypeID:1,      
        FirstName: "Tony",      
        LastName : "Smith",       
        Phone    : "987009879871",      
        Email    : "tony@gmail.com",      
        PasswordHash: "#gghuygiuhvfu$fgddf",   
        PasswordSalt:"$gjhghhjj$" ,  
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:7,                    
        UserTypeID:2,      
        FirstName: "Johny",      
        LastName : "Smith",       
        Phone    : "987987966871",      
        Email    : "johny@gmail.com",      
        PasswordHash: "#gghbuygiuhu$fgddf",   
        PasswordSalt:"$gjhbnghj$" , 
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    },
    {
        ID:8,                    
        UserTypeID:1,      
        FirstName: "tom",      
        LastName : "Smith",       
        Phone    : "9879834579871",      
        Email    : "tom@gmail.com",      
        PasswordHash: "#gghuhygiuhu$fgddf",   
        PasswordSalt:"$gjhghjff$" ,    
        IsActive     : true,  
        AuthenticationTypeID:3,
        CreatedOn     :new Date(),      
        UpdatedOn     :new Date()
    }
]
