export const userPostData: any[] = [
    {
        ID: 1,               
        UserID:1,               
        PostDateTime: new Date(),        
        PostText:"New video",             
        PostFileUrl: "http://www.abcd.com",         
        PostContentType:"video",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:1,          
        UserPageID:1,           
        PostAvailability:"Public",    
        IsActive:true             
    },
    {
        ID: 2,               
        UserID:3,               
        PostDateTime: new Date(),        
        PostText:"New image",             
        PostFileUrl: "http://www.efgh.com",         
        PostContentType:"Image",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:2,          
        UserPageID:1,           
        PostAvailability:"Connections",    
        IsActive:true             
    },
    {
        ID: 3,               
        UserID:2,               
        PostDateTime: new Date(),        
        PostText:"New post",             
        PostFileUrl: "http://www.hij.com",         
        PostContentType:"Document",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:3,          
        UserPageID:1,           
        PostAvailability:"Group",    
        IsActive:true             
    },
    {
        ID: 4,               
        UserID:8,               
        PostDateTime: new Date(),        
        PostText:"New post",             
        PostFileUrl: "http://www.klmn.com",         
        PostContentType:"video",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:1,          
        UserPageID:1,           
        PostAvailability:"Public",    
        IsActive:true             
    },
    {
        ID: 5,               
        UserID:6,               
        PostDateTime: new Date(),        
        PostText:"New post",             
        PostFileUrl: "http://www.xyz.com",         
        PostContentType:"document",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:9,          
        UserPageID:1,           
        PostAvailability:"Group",    
        IsActive:true             
    },
    {
        ID: 6,               
        UserID:5,               
        PostDateTime: new Date(),        
        PostText:"New image",             
        PostFileUrl: "http://www.abcde.com",         
        PostContentType:"image",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:6,          
        UserPageID:1,           
        PostAvailability:"Connections",    
        IsActive:true             
    },
    {
        ID: 7,               
        UserID:7,               
        PostDateTime: new Date(),        
        PostText:"New post",             
        PostFileUrl: "http://www.abcdef.com",         
        PostContentType:"video",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:5,          
        UserPageID:1,           
        PostAvailability:"Public",    
        IsActive:true             
    },
    {
        ID: 8,               
        UserID:4,               
        PostDateTime: new Date(),        
        PostText:"New post",             
        PostFileUrl: "http://www.abcdjk.com",         
        PostContentType:"image",      
        TotalLikes:0,                           
        TotalShares:0,         
        TotalComments:0,        
        PromotionID:4,          
        UserPageID:1,           
        PostAvailability:"Group",    
        IsActive:true             
    }
]